export const GET_ERRORS = "GET_ERROR"
export const GET_QUESTIONS = "GET_QUESTIONS"
export const GET_QUESTIONS_CATEGORY = "GET_QUESTIONS_CATEGORY"
export const GET_QUESTION = "GET_QUESTION"
export const DELETE_QUESTION = "DELETE_QUESTION"

export const GET_QUESTION_ANSWERS = "GET_QUESTION_ANSWERS"
export const DELETE_QUESTION_ANSWER = "DELETE_QUESTION_ANSWER"

